### ISSUE TITLE
Package generation task sometimes returns success but doesn't create a package

### ISSUE THREAD

**Issue by tahme** [CSCfi/fairdata-download-service#1]
Yesterday, I created a new dataset and published it in Metax test. Afterwards, I tried to create a download package by POSTing this to the download service test instance:
```
{"dataset":"d82dc30c-f095-4323-92ef-422f5478baaa","scope":["/prj_112_root/science_data_C"]}
```

The request was successful and returned
```
{
    "created": true,
    "dataset": "d82dc30c-f095-4323-92ef-422f5478baaa",
    "partial": [
        {
            "initiated": "2021-01-19T13:18:11+00:00",
            "scope": [
                "/prj_112_root/science_data_C"
            ],
            "status": "PENDING"
        }
    ]
}
```
but `GET /requests?dataset=d82dc30c-f095-4323-92ef-422f5478baaa` gave
```
{'error': "No active file generation tasks was found for dataset 'd82dc30c-f095-4323-92ef-422f5478baaa'", 'name': 'Not Found'}
```

Repeated attempts produced similar results. Today the same dataset I tested yesterday works correctly, but when I create a new dataset, it has the same issue.

It was speculated that maybe the download service doesn't take time zones into account when comparing timestamps. Metax datasets currently use +02:00 but the download service uses +00:00, so a new dataset could look like it was modified after the package creation request.

**Comment by anteroncsc** [comment]
Fix included in version 1.0.1
